apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dotnet-app
spec:
  destination:
    name: ''
    namespace: prod
    server: 'https://kubernetes.default.svc'
  source:
    path: config/dev
    repoURL: 'https://github.com/lugosidomotor/app2.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
